# Generated by Django 4.1.4 on 2023-04-20 05:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dandhacontrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='recharge_date',
            new_name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price_monthly',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='payment_collected',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='recharge',
            name='payment_mode',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='device',
            name='add_on_desc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='frequency',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='recharge',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='add_on_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='device',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='recharge_entry',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dandhacontrol.device')),
                ('payment_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dandhacontrol.paymentmode')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
